name: ~peppe
url: "http://peppelab.altervista.org"

plugins:
  - jekyll-sitemap
  - jekyll-assets

markdown_ext: markdown,md,text,html
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: null
  
sass:
  style: full

assets:
  compression: true
  plugins:
    css:
      autoprefixer: {}
    img:
      optim: {}

exclude: [makefile,lftp.script]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:title:output_ext
      layout: "post"
  -
    scope:
      path: ""
      type: "storiarte"
    values:
      permalink: /:collection/:name:output_ext
      layout: "default"

collections:
  storiarte:
    output: true
