name: ~peppe
url: "http://peppelab.altervista.org"

plugins:
  - jekyll-sitemap

markdown_ext: markdown,md,text,html
markdown: kramdown
highlighter: rouge

sass:
  style: full

exclude: [makefile]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:title:output_ext
      layout: "post"
  -
    scope:
      path: ""
      type: "storiarte"
    values:
      permalink: /:collection/:name:output_ext
      layout: "default"

collections:
  storiarte:
    output: true
