name: ~peppe 
url: "http://peppelab.altervista.org"
gems: [jekyll-pandoc]
markdown: PandocProcessor
pandoc: 
  extensions: [mathjax,smart,normalize]
  highlight-style: pygments
sass:
  style: compressed
markdown_ext: markdown,md,text,html
highlighter: pygments
permalink: /blog/:year/:title.html
exclude: [makefile]
